---
title: "Academic Blog"
---

<h2><span class="fa fa-file-text-o" aria-hidden="true"></span> Posts</h2> 
<hr>

<!-- 2018 March Madness -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Simulating-2018-NCAA-March-Madness-Tournament-Performance-in-R.html" class="postLink"> Simulating 2018 NCAA March Madness Tournament Performance in R</a></h3>

<span class="glyphicon glyphicon-time"></span> March 20, 2018
<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>

A few of us graduate students decided it would be fun to simulate this year's NCAA Men's National Championship tournament using R. When we all met to discuss our method to simuluate tournament performance, we quickly realized several methods emerged...

<br>

<!-- Multi-level Model NHL -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Multilevel-Modeling-in-R-with-NHL-Power-Play-Data.html" class="postLink"> Multilevel Modeling in R with NHL Power Play Data</a></h3>

<span class="glyphicon glyphicon-time"></span> February 11, 2018
<span class="label label-primary">Academic</span>
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>
<span class="label label-danger">Power Play</span>

This post serves as both a tutorial on how to perform multilevel modeling in R and an analysis that provides insight to how powerplay goals in the NHL have changed across 10 years. Readers will learn how to explore data using plots, use R to fit linear models, and how to extract inferences from the results.

<br>

<!-- Lit Review -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Writing-a-Literature-Review.html" class="postLink"> Writing a Literature Review</a></h3>

<span class="glyphicon glyphicon-time"></span> September 25, 2017
<span class="label label-primary">Academic</span>

I recently completed my first comprehensive literature review as part of a graduate school milestone project. Before starting, I sought guidance from online blogs and university workshops held by our library. The tips I learned from these resources were extremely helpful, but not everything worked for me. This is simply a list of things that worked/did not work for me during the reading and writing process of my literature review...

<br>

<!-- Xbox Controllers and Eprime -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Using-Xbox-Controllers-and-Sending-EEG-Triggers-with-E-Prime.html" class="postLink"> Using Xbox Controllers and Sending EEG Triggers with E-Prime</a></h3>

<span class="glyphicon glyphicon-time"></span> June 12, 2017
<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>
<span class="label label-success">E-Prime</span>
<span class="label label-warning">EEG</span>

I just spent an entire week wrangling the E-Prime beast and I've lived to tell the tale. I was able to successfully integrate an Xbox controller to accept participant responses as well as communicate these to an EEG system as triggers. This wouldn't have been possible without the help of benevolent bloggers and discussions on E-Prime's Google group, so thank you all! I'll point out these information sources along the way...

<br>

<!-- ggplot2 Histogram Logo Fail -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-ggplot2-Histogram-Logo-Fail.html" class="postLink"> ggplot2 Histogram Logo Fail</a></h3>

<span class="glyphicon glyphicon-time"></span> May 15, 2017
<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>

When I first started creating this website (in WordPress), I thought it would be cool have have my own logo. Why not, right? I figured I'd go super nerdy and have a cool histogram plot with a density curve through it. I had just finished reading Hadley Wickham's ggplot2 [book](https://github.com/hadley/ggplot2-book) and I was excited to put some of those newly learned skills to use...

<br>

<!-- Stop Using Excel to Preprocess E-Prime Data -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Stop-Using-Excel-to-Preprocess-E-Prime-Data.html" class="postLink"> Stop Using Excel to Preprocess E-Prime Data</a></h3>

<span class="glyphicon glyphicon-time"></span> May 15, 2017
<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>
<span class="label label-success">E-Prime</span>

Excel is a great tool for processing data. Whether it's calculating a quick average, standard deviation, or t-test, Excel is fast and simple to learn and use. In fact, most of my colleagues use Excel to preprocess their data from experiments programmed in E-Prime, a software tool for running psychological experiments. However, preprocessing your E-Prime data in Excel will...

<br>