---
title: "Consulting"
format:
  html:
    toc: true
    toc-depth: 2
    toc-location: left
    smooth-scroll: true
---

Welcome to MJK Consulting! I help clients with their data science needs, including data wrangling, statistical modeling, data visualization, and writing. **Feel free to book an appointment for a free quote:**

<!-- Google Calendar Appointment Scheduling begin -->
<link href="https://calendar.google.com/calendar/scheduling-button-script.css" rel="stylesheet">
<script src="https://calendar.google.com/calendar/scheduling-button-script.js" async></script>
<script>
(function() {
  var target = document.currentScript;
  window.addEventListener('load', function() {
    calendar.schedulingButton.load({
      url: 'https://calendar.google.com/calendar/appointments/schedules/AcZssZ3DtXDElK8ki2DFP0NsiTzyDO6wqhfuM1Hcalmnr5yycvv2wmXZUB_usIrYNNFIUAvi26joEdnO?gv=true',
      color: '#039BE5',
      label: 'Book an appointment',
      target,
    });
  });
})();
</script>
<!-- end Google Calendar Appointment Scheduling -->

## Areas of expertise

* R/RStudio coach
* Statistics
  - Linear modeling (analysis of variance, linear mixed models, logistic regression)
  - Principal component analyses
  - Survival modeling (Kaplan-Meier estimation, Cox Proportional Hazards, Accelerated Failure Time modeling)
* Data visualization
* Data wrangling and cleaning
* Data analysis pipelines
* Git/GitHub
* Website development
* APIs
* Shiny Apps
* Sports analytics
* MATLAB
* EEG/fMRI processing
* Experimental Design/E-Prime
* Academic writing
* Blogging