---
title: ""
---

<br>

<!-- MY BLOGS -->

<h2><span class="fa fa-paper-plane-o" aria-hidden="true"></span> My Blogs</h2> 
<hr>

<h3><span class="fa fa-newspaper-o" aria-hidden="true"></span><a href="academicblog.html"> Academic Blog</a></h3> 

<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>
<span class="label label-success">E-Prime</span>
<span class="label label-warning">EEG</span>

As a cognitive neuroscientist, my projects are a blend of cognitive psychology, computer science, statistics, neuroimaging, and neuroscience principles. This blog serves mainly as resource to myself (so I can refer to how I did something), but also aims to teach others.

<h3><span class="fa fa-newspaper-o" aria-hidden="true"></span><a href="theblueline.html"> The Blue Line</a></h3> 

<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>
<span class="label label-danger">Power Play</span>

I love the sport of hockey. In my spare time, I like to apply some of the statistical techniques that I've learned in my classes and research projects to hockey data. This hockey analytics blog serves to help hone my data science skills, teach R, and (hopefully) provide new insights to this amazing sport.

<br>

<!-- RECENT POSTS -->

<h2><span class="fa fa-file-text-o" aria-hidden="true"></span> Recent Posts</h2> 
<hr>

<!-- 2018 March Madness -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Simulating-2018-NCAA-March-Madness-Tournament-Performance-in-R.html" class="postLink"> Simulating 2018 NCAA March Madness Tournament Performance in R</a></h3>

<span class="glyphicon glyphicon-time"></span> March 20, 2018
<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>

When a bunch of grad students get together to simulate college basketball tournament performance using R.

<br>

<!-- Multi-level Model NHL -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Multilevel-Modeling-in-R-with-NHL-Power-Play-Data.html" class="postLink"> Multilevel Modeling in R with NHL Power Play Data</a></h3>

<span class="glyphicon glyphicon-time"></span> February 11, 2018
<span class="label label-primary">Academic</span>
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>
<span class="label label-danger">Power Play</span>

A collaboration post about multilevel modeling in R using professional hockey data from the NHL.

<br>

<!-- Lit Review -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Writing-a-Literature-Review.html" class="postLink"> Writing a Literature Review</a></h3>

<span class="glyphicon glyphicon-time"></span> September 25, 2017
<span class="label label-primary">Academic</span>

A post about writing my first literature review. Things that worked/did not work for me.

<br>

<!-- Xbox Controllers and Eprime -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Using-Xbox-Controllers-and-Sending-EEG-Triggers-with-E-Prime.html" class="postLink"> Using Xbox Controllers and Sending EEG Triggers with E-Prime</a></h3>

<span class="glyphicon glyphicon-time"></span> June 12, 2017
<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>
<span class="label label-success">E-Prime</span>
<span class="label label-warning">EEG</span>

A post about interfacing E-Prime 2.0 with an Xbox controller and passing stimulus/response triggers.

<br>

<!-- ggplot2 histogram logo fail -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-ggplot2-Histogram-Logo-Fail.html" class="postLink"> ggplot2 Histogram Logo Fail</a></h3>

<span class="glyphicon glyphicon-time"></span> May 15, 2017
<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>

A (probably) pointless post about forcing spaces in ggplot2 histograms.

<br>

<!-- Stop Using Excel to Preprocess E-Prime Data -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-Stop-Using-Excel-to-Preprocess-E-Prime-Data.html" class="postLink"> Stop Using Excel to Preprocess E-Prime Data</a></h3>

<span class="glyphicon glyphicon-time"></span> May 15, 2017
<span class="label label-primary">Academic</span>
<span class="label label-default">R</span>
<span class="label label-success">E-Prime</span>

A post demonstrating an efficient data pipeline for E-prime users.

<br>

<!-- The Last Decade NHLs Best and Worst Power Play Teams -->

<h3><span class="fa fa-sticky-note-o" aria-hidden="true"></span><a href="post-The-Last-Decade-NHLs-Best-and-Worst-Power-Play-Teams.html" class="postLink"> The Last Decade: NHL’s Best and Worst Power Play Teams</a></h3>

<span class="glyphicon glyphicon-time"></span> May 15, 2017
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>
<span class="label label-danger">Power Play</span>

A hockey analytics post about 5 vs. 4 NHL powerplays from 2007-2017.

<br>


<!-- disqus comment counter LEAVE HERE AT BOTTOM OF INDEX -->
<script id="dsq-count-scr" src="//mattkmiecik.disqus.com/count.js" async></script> 






