---
title: "My Experience in Industry (so far)"
author: "Matthew J. Kmiecik, PhD"
date: "21 January 2023"
format:
  html:
    toc: true
    toc-depth: 2
    toc-location: left
    smooth-scroll: true
---

I'm sitting on a flight from San Fransisco to Chicago, a trip I will frequently be taking in the next 5 months, and feeling somewhat compelled to begin blogging again. There's an intense debate out there about academia vs. industry and it's something I've given so much thought about since transitioning from an academic postdoc to an industry postdoc. There's this overwhelming pressure building inside that I feel I must express, but I have no idea why. Is it to help others that were in a similar situation that I was one year ago? Is it to justify this decision to go to industry after pouring everything I had into an academic career that did not pan out? Is it to overcome the guilt and feeling of letting others down that supported me and encouraged me to continue in academia? Is it to show others how much pain and internal turmoil it can take on someone when going through this thought process? It perhaps is a mixture of these things; but somewhat a reflection of how academia was not the dream that was sold to me. Now if you are looking for a piece bashing academia, this is not the post for you. I have many wonderful friends and colleagues in academia and I respect and I think a lot of good can come from academia. However, currently the system is, in my mind, unsustainable, counterproductive, and incredibly difficult to navigate if you are first generation. Given that I am a white male, I feel inequipped to speak on behalf of those that are women, minorities, or part of the LGBTQ+ community; however, I imagine their struggles in academia are even more difficult than mine.

Here are just some of my thoughts on the process of my transition to industry from academic.

# Undergrad

First, let me provide some background on my experiences as everyones journey is different.

I entered my undergraduate education at Loyola University Chicago on a premed track with ambitions to become a pediatrician, a goal I set for myself in the 5th grade. All my childhood I was told that I was smart, to stay in school, and to become a physician so that I can make a lot of money. [footnote here about how dad told me to stay in school when we were painting my condo after phd] I'm sure many first generation children of immigrant parents can relate. My parents were incredibly financially supportive of my undergraduate education and I luckily only had to take out a very reasonable amount of student loans; however, we had no idea what we were doing when applying to colleges. Which colleges were good? Which ones are big? Which have good acceptance rates for future medicine? Which had good research programs? Which have strong programs? I could not help feeling that I was surrounded with peers that were always a step ahead at knowing these things. It's hard to imagine the advantages that having parents that went to university have on these formative years [I've heard that some people actually give their parents draft of their papers to proofread...what!]; the vocabulary was on a different level for me. I don't think I even knew what a PhD was and what it entailed; how one received a PhD. I heard of this thing called graduate school, but it seemed mystical.

Nevertheless, I was told that in order to get into med school, that I should do research on campus. I had no idea how this enterprise worked and how to get started. Fortunately, I was taking an upper level psychology class (my major) and the professor emailed the class asking if anyone was interested in being a research assistant in her lab. This was it! This was my in! I immediately emailed back, and within a week I was getting trained in the lab and running participants. [annecdote here about rude encounter during testing]. I worked with these older students called "grad students". I didn't quite understand what a grad student, but assumed that they had graduated from college and they were doing extra school. My role was quite minimal, just running subjects through surveys (i.e., no data analysis or writing). I did this for a year, but did not return the subsequent Fall so that I can focus on increasing my GPA. [annecdote here about learning how to study]

My sophmore year was quite formative; I learned how to study properly and began discovering subjects in psychology that were fascinating to me, mainly cognitive psychology [Tim Miura footnote] and judgment and decision making. After gaining confidence in my study techniques and with my grades up, I decided it was time for me to join a lab again. I now knew the system; professors at a university do research in addition to their teaching and they need help to do so. So I got connected in a cognitive neuroscience laboratory that changed my life. I discovered that you could study someone's cognition by presenting them with carefully designed experiments recording their brainwaves using scalp EEG. Out would come a flurry of numbers that you could organize and analyze in excel and various software programs. It was like solving a puzzle and I loved it. I found myself working late in the night on spreadsheets and data analysis, and studying seemed so boring. I was studying the unknown and it was thrilling. My undergraduate mentor gave me guidance on projects and I was largely independent in creating experiments, running participants, analyizng data. I learned about presenting at conferences, making posters, publishing papers, and what a grad studnet was. A creeping realization was happening; I no longer wanted to be a med student. I wanted to be a cognitive neuroscientist. I tried to suppress this as much as I could to appease my parents and everyone I told before that I was going to be a pediatrician. I even enrolled in an MCAT course and was seriosuly considering the MD/PhD. The thought of studying and memorizing things ad nauseum in med school was truly unappealing to me relative to what I could be doing in cogntiive neuroscience. I am glad that I followed my heart and chose cognitive neuroscience; although this dissapointed my parents, I knew I made the right decision. Since that day forward, I can say with confidence that ever since that day I have never "worked". When I wake up each morning and take a shower, I am thinkng about the next step in my projects and am excited to work on them every single day. I tell people that I go to work, but it never feels like that. I realize that's a rare thing to have, but I'm grateful to have found it so early in my life.

# Gap Year

[text here about lab manager position]

Similarly to applying to college, applying to grad school I was more in the dark. Although I had the help of my undergraduate mentors, I had no idea what I was doing. I was carving a path for myself. I had no idea what an R1 university was, how it was different than an R2. Which programs were good? What is the NIH? What are grants? I knew of famous schools, like Harvard or Yale, and I of course wasn't going to apply to those, but I realize now that where you go to graduate school makes a huge difference. All 20% of acadmeic jobs are filled by these 6 univerisites [cite that nautre paper]. I'm not saying that you will be a unsuccessful academic if you do not attend these schools, but it makes you think about your odds or chances. Knowing these will help better prepare you for alternative career paths in graduate school something I highly recommend and think is what is broken in academia. I've realized that academia is a pyramid scheme[reference to wikipedia or something] and if you want to be sucessful you are going to have to play along. Hoepfully I do a good job eluciating how acadmeia is a ponzi scheme with examples I've noticed throughout.

My GRE scores were quite average and therefore didn't get considered for programs with cutoffs. However, my research experience was quite strong: I had several conference posters, a conference paper with an oral presentation[footnote about how travel is cool in academia; point is to salute acadmia a little], which also won an award at my undergraduate institution, and a paper in press (middle author). I applied to 6 schools, got 3 interviews, and 1 acceptance (which I went). My undergraduate mentor went to graduate school with my graduate advisor which probably increased my chances as well. I was also a good fit for the lab so it worked out.

During my 5 years in grad school my institution and department had immense success and were well funded through the NIH, DOD, and private donors, and reached R1 status quickly. I think I was decently productive in graduate school, publishing four papers during my 5.5 years. Of these, 2 were first author from independent projects, 1 was a first author paper I finished up from undergrad, and 1 was a protocol paper that I contributed a small piece and therefore 4th author. In comparison to some other bigger labs, I feel like my experience with papers and publishing has been an uphill battle. It seemed that if I wanted to have a paper I would have to be a first author. I an envious of the labs that are very collaborative and although projects are mainly spearheadded 

