---
title: "The Blue Line"
---

My infatuation (some say obsession) with hockey began during my undergrad in the city of Chicago. I was fortunate enough to see the Blackhawks win the Stanley Cup when I was in Chicago not once, but TWICE! As I have grown to appreciate and love hockey, I found another outlet to further submerse myself in the sport — statistics!  A few ideas I have played around with have been the power play, face-offs, potential trends across time, and seeing if there is anything that can predict the likelihood of a Stanley Cup victory!

Doors closing… Welcome to the Blue Line.

<h2><span class="far fa-file-alt" aria-hidden="true"></span> Posts</h2> 
<hr>

<!-- BlackhawkUp Posts -->

<h3><span class="far fa-sticky-note" aria-hidden="true"></span><a href="https://blackhawkup.com/2019/07/19/chicago-blackhawks-scoring-density-analysis-2018-2019-season/" class="postLink" target="_blank"> Chicago Blackhawks: Scoring Density Analysis for the 2018-2019 Season</a></h3>

<span class="far fa-clock"></span> July 19th, 2019
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>

We’ve all heard Wayne Gretzky’s famous quote, “You miss 100% of the shots you don’t take.” Historically, the Chicago Blackhawks have taken Gretzky’s advice to heart and are one of the top four most efficient offenses since 2007 (for a statistical analysis, see my previous article)...

<br />

<h3><span class="far fa-sticky-note" aria-hidden="true"></span><a href="https://blackhawkup.com/2019/06/27/chicago-blackhawks-efficient-offensive-machine/" class="postLink" target="_blank"> Chicago Blackhawks: An Efficient Offensive Machine</a></h3>

<span class="far fa-clock"></span> June 27th, 2019
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>

When watching Game 7 of the Dallas and St. Louis playoff series this year, I received a text from a friend of mine commenting on the sheer discrepancy of shots on goal between the teams...

<br />

<h3><span class="far fa-sticky-note" aria-hidden="true"></span><a href="https://blackhawkup.com/2019/05/14/q-colliton-first-67-games-blackhawks-head-coach/" class="postLink" target="_blank"> Coach Q vs. Jeremy Colliton: First 67 Games As Blackhawks’ Head Coach</a></h3>

<span class="far fa-clock"></span> May 15th, 2019
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>

Coach Q had become Chicago’s steadfast leader and genius architect, constructing synergistic line combinations and masterfully adapting to player matchups throughout his 3 Stanley Cup winning tenure...

<br />

<h3><span class="far fa-sticky-note" aria-hidden="true"></span><a href="https://blackhawkup.com/2019/04/09/chicago-blackhawks-patrick-kane-scoring/" class="postLink" target="_blank"> Chicago Blackhawks: analyzing Patrick Kane’s career scoring tendencies</a></h3>

<span class="far fa-clock"></span> April 9th, 2019
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>

The Chicago Blackhawks‘ own Patrick “Showtime” Kane. The breaker of records, the daddy of dangles, the lighter of lamps. No matter what you call him, Kaner has had a tremendous year and is deserving of some hardware at the end of the season...

<br />

<h3><span class="far fa-sticky-note" aria-hidden="true"></span><a href="https://blackhawkup.com/2019/04/18/blackhawks-player-grades-patrick-kane/" class="postLink" target="_blank"> Chicago Blackhawks 2018-19 Player Grades: Patrick Kane</a></h3>

<span class="far fa-clock"></span> April 19th, 2019
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>

Patrick Kane battled through adversity at every corner this season. His ability to take over a game, frequent double shifts (including powerplays) and his knack for finding teammates with precise passes injected hope into the bloodstream of ‘Hawks fans every time he took the ice...

<br />

<!-- Blackhawks PCA -->

<h3><span class="far fa-sticky-note" aria-hidden="true"></span><a href="https://mattkmiecik.com/post-Exploring-11-Years-of-Chicago-Blackhawks-Data-using-Principal-Components-Analysis.html" class="postLink"> Exploring 11 Years of Chicago Blackhawk’s Data using Principal Components Analysis</a></h3>

<span class="far fa-clock"></span> March 7, 2019
<span class="label label-primary">Academic</span>
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>

In this post we explore 11 seasons (2007 - 2018) of team summary data from the Chicago Blackhawks of the National Hockey League (NHL). Our question was, “Are there any summary measures, such as goals scored or save percentage, that predict playoff performance or championship wins?”...

<br>

<!-- Multi-level Model NHL -->

<h3><span class="far fa-sticky-note" aria-hidden="true"></span><a href="post-Multilevel-Modeling-in-R-with-NHL-Power-Play-Data.html" class="postLink"> Multilevel Modeling in R with NHL Power Play Data</a></h3>

<span class="far fa-clock"></span> February 11, 2018
<span class="label label-primary">Academic</span>
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>

This post serves as both a tutorial on how to perform multilevel modeling in R and an analysis that provides insight to how powerplay goals in the NHL have changed across 10 years. Readers will learn how to explore data using plots, use R to fit linear models, and how to extract inferences from the results.

<br>

<!-- The Last Decade NHLs Best and Worst Power Play Teams -->

<h3><span class="far fa-sticky-note" aria-hidden="true"></span><a href="post-The-Last-Decade-NHLs-Best-and-Worst-Power-Play-Teams.html" class="postLink"> The Last Decade: NHL’s Best and Worst Power Play Teams</a></h3>

<span class="far fa-clock"></span> May 15, 2017
<span class="label label-info">Hockey Analytics</span>
<span class="label label-default">R</span>

So you are watching your favorite NHL team and they finally draw a powerplay. Awesome! The ice opens up with the missing player and it shouldn't be too hard to score...right? As a previous water polo player, I know what it is like to endure the wrath of a furious coach after a missed man advantage opportunity. In my experience, coaches semed convinced that the man-up should lead to a goal 100% of the time. But how important is this seemingly advantageous situation in the NHL?...

<br>